#1. Import the NUMPY package under the name np.

In [1]:
import numpy as np
import random


#2. Print the NUMPY version and the configuration.

In [2]:
print(np.__version__)
print(np.show_config())


1.18.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None



#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
 Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?



In [3]:
a= np.random.random((2,3,5))

d = np.random.rand(2,3,5)


#4. Print a.

In [4]:
print(a)

[[[0.71171712 0.16889368 0.18717847 0.27943098 0.58252027]
  [0.84928841 0.52146406 0.45967857 0.18852119 0.53064599]
  [0.50775317 0.34790079 0.39183347 0.87077316 0.70344832]]

 [[0.68111903 0.99840842 0.89571824 0.56652717 0.99316401]
  [0.50595123 0.04639738 0.13355726 0.66601331 0.7918437 ]
  [0.94452592 0.02654197 0.70309432 0.19237978 0.8704439 ]]]


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"


In [5]:
b = np.ones((5,2,3))


#6. Print b.



In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#7. Do a and b have the same size? How do you prove that in Python code?

In [7]:
np.array_equal(a,b)

False


#8. Are you able to add a and b? Why or why not?



In [13]:
np.concatenate([a,b])
print(c)
#solo las matrices con la misma escala se pueden concatenar



ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c"

In [14]:
c= b.reshape(2, 3, 5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?


In [18]:
d = np.concatenate([a,c])
print(d)
#Ahora se pueden añadir por que tienen el mismo numero de columnas filas y dimensiones

[[[0.71171712 0.16889368 0.18717847 0.27943098 0.58252027]
  [0.84928841 0.52146406 0.45967857 0.18852119 0.53064599]
  [0.50775317 0.34790079 0.39183347 0.87077316 0.70344832]]

 [[0.68111903 0.99840842 0.89571824 0.56652717 0.99316401]
  [0.50595123 0.04639738 0.13355726 0.66601331 0.7918437 ]
  [0.94452592 0.02654197 0.70309432 0.19237978 0.8704439 ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]]


11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

#12. Multiply a and c. Assign the result to e.

In [19]:
e = a*c
print(e)

[[[0.71171712 0.16889368 0.18717847 0.27943098 0.58252027]
  [0.84928841 0.52146406 0.45967857 0.18852119 0.53064599]
  [0.50775317 0.34790079 0.39183347 0.87077316 0.70344832]]

 [[0.68111903 0.99840842 0.89571824 0.56652717 0.99316401]
  [0.50595123 0.04639738 0.13355726 0.66601331 0.7918437 ]
  [0.94452592 0.02654197 0.70309432 0.19237978 0.8704439 ]]]


#13. Does e equal to a? Why or why not?


In [20]:
np.array_equal(a,e)

True

In [ ]:
#son iguales a y e por que e es el np.array a multiplicando sus valores por 1 por eso sale la misma np.array

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [25]:
d_max =  np.max(d)
d_min =  np.min(d)
d_mean =  np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.0
0.026541966977424725
0.7719455550068249


#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [32]:
f =np.empty([2,3,5])


#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""


In [35]:
def asignar(x):
    
    memory = []
    for x in range(0,size):
        memory.append([])
        for y in range(0,size):
            memory[x].append([])
            for z in range(0,size):
                   memory[x][y].append(0)       
                if e > d_mean and e < d_max:
                    return x.append(75)
                if e > d_min and e < d_mean:
                    return x.append(25)
                if e == d_mean:
                    return x.append(50)
                if e == d_min:
                    return x.append(0)
                if e == d_max:
                    return x.append(100)
f =asignar(d)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [34]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

'\n#17. Print d and f. Do you have your expected f?\nFor instance, if your d is:\narray([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],\n        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],\n        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],\n\n       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],\n        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],\n        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])\n\nYour f should be:\narray([[[ 75.,  75.,  75.,  25.,  75.],\n        [ 75.,  75.,  25.,  25.,  25.],\n        [ 75.,  25.,  75.,  75.,  75.]],\n\n       [[ 25.,  25.,  25.,  25., 100.],\n        [ 75.,  75.,  75.,  75.,  75.],\n        [ 25.,  75.,   0.,  75.,  75.]]])\n'

In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""