# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [1]:
# import numpy and pandas
import pandas as pd
import numpy as np
import scipy.stats
from statsmodels.stats.proportion import proportions_ztest


# Challenge 1 - Exploring the Data

In this challenge, we will examine all salaries of employees of the City of Chicago. We will start by loading the dataset and examining its contents

In [2]:
# Run this code:

salaries = pd.read_csv('../Current_Employee_Names__Salaries__and_Position_Titles.csv')

Examine the `salaries` dataset using the `head` function below.

In [3]:
# Your code here:
salaries.head(3)


Name                              Job Titles  \
0    AARON,  JEFFERY M                                SERGEANT   
1      AARON,  KARINA   POLICE OFFICER (ASSIGNED AS DETECTIVE)   
2  AARON,  KIMBERLEI R                CHIEF CONTRACT EXPEDITER   

         Department Full or Part-Time Salary or Hourly  Typical Hours  \
0            POLICE                 F           Salary            NaN   
1            POLICE                 F           Salary            NaN   
2  GENERAL SERVICES                 F           Salary            NaN   

   Annual Salary  Hourly Rate  
0       101442.0          NaN  
1        94122.0          NaN  
2       101592.0          NaN

We see from looking at the `head` function that there is quite a bit of missing data. Let's examine how much missing data is in each column. Produce this output in the cell below

In [4]:
# Your code here:
#missdf = pd.DataFrame({'column_name': salaries.columns,
#                     'percent_missing': salaries.isnull().mean()})

#missdf.sort_values(["percent_missing"], ascending=False)
salaries.isnull().sum()

Name                     0
Job Titles               0
Department               0
Full or Part-Time        0
Salary or Hourly         0
Typical Hours        25161
Annual Salary         8022
Hourly Rate          25161
dtype: int64

Let's also look at the count of hourly vs. salaried employees. Write the code in the cell below

In [5]:
# Your code here:

salaries["Salary or Hourly"].value_counts() 

Salary    25161
Hourly     8022
Name: Salary or Hourly, dtype: int64

What this information indicates is that the table contains information about two types of employees - salaried and hourly. Some columns apply only to one type of employee while other columns only apply to another kind. This is why there are so many missing values. Therefore, we will not do anything to handle the missing values.

There are different departments in the city. List all departments and the count of employees in each department.

In [6]:
# Your code here:
salaries["Department"].value_counts() 

POLICE                   13414
FIRE                      4641
STREETS & SAN             2198
OEMC                      2102
WATER MGMNT               1879
AVIATION                  1629
TRANSPORTN                1140
PUBLIC LIBRARY            1015
GENERAL SERVICES           980
FAMILY & SUPPORT           615
FINANCE                    560
HEALTH                     488
CITY COUNCIL               411
LAW                        407
BUILDINGS                  269
COMMUNITY DEVELOPMENT      207
BUSINESS AFFAIRS           171
COPA                       116
BOARD OF ELECTION          107
DoIT                        99
PROCUREMENT                 92
INSPECTOR GEN               87
MAYOR'S OFFICE              85
CITY CLERK                  84
ANIMAL CONTRL               81
HUMAN RESOURCES             79
CULTURAL AFFAIRS            65
BUDGET & MGMT               46
ADMIN HEARNG                39
DISABILITIES                28
TREASURER                   22
HUMAN RELATIONS             16
BOARD OF

# Challenge 2 - Hypothesis Tests

In this section of the lab, we will test whether the hourly wage of all hourly workers is significantly different from $30/hr. Import the correct one sample test function from scipy and perform the hypothesis test for a 95% two sided confidence interval.

In [7]:
# Your code here:
#Ho El salario/h de los trabajadores por horas es = $ 30 / hora
#H1 El salario/h de los trabajadores por horas es =! $ 30 / hora
 
a = salaries[salaries['Hourly Rate'].isnull() == False]['Hourly Rate']

#stats.ttest_1samp(a, popmean)
#Salario=30


statictic,pvalue = scipy.stats.ttest_1samp(a,30)
print(statictic,pvalue)


if pvalue < 0.05:  
    print("Hipotesis nula rechazada")
else:
    print("La hipotesis nula no se puede rechazar")


20.6198057854942 4.3230240486229894e-92
Hipotesis nula rechazada


We are also curious about salaries in the police force. The chief of police in Chicago claimed in a press briefing that salaries this year are higher than last year's mean of $86000/year a year for all salaried employees. Test this one sided hypothesis using a 95% confidence interval.

Hint: A one tailed test has a p-value that is half of the two tailed p-value. If our hypothesis is greater than, then to reject, the test statistic must also be positive.

In [8]:
# Your code here p:0.02 < 0.025 (de 0.5/2) 
#Ho los salarios de este año son menores o iguales que los del año pasado
#H1 los salarios de este año son mayores que los del año pasado (86.000)

a = salaries[(salaries['Annual Salary'].isnull() == False) & (salaries['Department']=='POLICE')]['Annual Salary']

#stats.ttest_1samp(a, popmean)
#Salario=30

statictic,pvalue = scipy.stats.ttest_1samp(a,86000)
print(statictic,pvalue)


if pvalue < 0.025:     #0.05/2
    print("Hipotesis nula rechazada")
else:
    print("La hipotesis nula no se puede rechazar")

3.081997005712994 0.0020603403550965137
Hipotesis nula rechazada


Using the `crosstab` function, find the department that has the most hourly workers. 

In [9]:
# Your code here:
df = pd.crosstab(salaries.Department, salaries['Salary or Hourly'])

df.sort_values(by='Hourly',ascending=False).head(3)

Salary or Hourly  Hourly  Salary
Department                      
STREETS & SAN       1862     336
WATER MGMNT         1513     366
OEMC                1273     829

The workers from the department with the most hourly workers have complained that their hourly wage is less than $35/hour. Using a one sample t-test, test this one-sided hypothesis at the 95% confidence level.

In [10]:
# Your code here:
#Ho su salario por hora es igual o superior a 35 $
#H1 su salario por hora es inferior a $ 35

a = salaries[(salaries['Department']=='STREETS & SAN') & (salaries['Salary or Hourly']=='Hourly')]['Hourly Rate']

#stats.ttest_1samp(a, popmean)
#Salario=35


statictic,pvalue = scipy.stats.ttest_1samp(a,35)
print(statictic,pvalue)


if pvalue < 0.05:  
    print("Hipotesis nula rechazada")
else:
    print("La hipotesis nula no se puede rechazar")

-9.567447887848152 3.3378530564707717e-21
Hipotesis nula rechazada


# Challenge 3 - Constructing Confidence Intervals

While testing our hypothesis is a great way to gather empirical evidence for accepting or rejecting the hypothesis, another way to gather evidence is by creating a confidence interval. A confidence interval gives us information about the true mean of the population. So for a 95% confidence interval, we are 95% sure that the mean of the population is within the confidence interval. 
).

To read more about confidence intervals, click [here](https://en.wikipedia.org/wiki/Confidence_interval).


In the cell below, we will construct a 95% confidence interval for the mean hourly wage of all hourly workers. 

The confidence interval is computed in SciPy using the `t.interval` function. You can read more about this function [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.t.html).

To compute the confidence interval of the hourly wage, use the 0.95 for the confidence level, number of rows - 1 for degrees of freedom, the mean of the sample for the location parameter and the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in SciPy.

In [11]:
# Your code here:
#95% (0.95) intervalo confianza salario medio por hora de todos los trabajadores por horas.
#número de filas - 1 para grados de libertad, l
#media de la muestra para el parámetro de ubicación y el error estándar para la escala. 
#El error estándar se puede calcular usando esta función en SciPy.

#scipy.stats.sem(a, axis=0, ddof=1, nan_policy='propagate')

a = salaries[salaries['Hourly Rate'].isnull() == False]['Hourly Rate']

se=scipy.stats.sem(a,ddof=(len(a)-1))

#interval(alpha, df, loc=0, scale=1)

scipy.stats.t.interval(0.95, a, a.mean(), se)

(array([7.51232632, 8.41016026, 8.21506596, ..., 8.21506596, 8.41370022,
        8.44705823]),
 array([58.06478911, 57.16695518, 57.36204948, ..., 57.36204948,
        57.16341521, 57.13005721]))

Now construct the 95% confidence interval for all salaried employeed in the police in the cell below.

In [12]:
# Your code here:
a = salaries[(salaries['Salary or Hourly'] == 'Salary') & (salaries['Department']=='POLICE')]['Annual Salary']

se=scipy.stats.sem(a,ddof=(len(a)-1))

#interval(alpha, df, loc=0, scale=1)

scipy.stats.t.interval(0.95, a, a.mean(), se)


(array([50674.41376419, 50674.38053251, 50674.37674383, ...,
        50673.93947888, 50674.35956855, 50674.37674383]),
 array([122298.41524207, 122298.44847376, 122298.45226244, ...,
        122298.88952738, 122298.46943772, 122298.45226244]))

# Challenge 4 - Hypothesis Tests of Proportions

Another type of one sample test is a hypothesis test of proportions. In this test, we examine whether the proportion of a group in our sample is significantly different than a fraction. 

You can read more about one sample proportion tests [here](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/SAS6-CategoricalData2.html).

In the cell below, use the `proportions_ztest` function from `statsmodels` to perform a hypothesis test that will determine whether the number of hourly workers in the City of Chicago is significantly different from 25% at the 95% confidence level.

In [13]:
# Your code here:
a = salaries[salaries['Salary or Hourly']=='Hourly']['Hourly Rate'].count()
b=salaries['Name'].count()
proportions_ztest(a, b ,0.25)

(-3.5099964213703005, 0.0004481127249057967)